# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
index:
   path: /
   defaults: { _controller: 'App\Controller\PagesController::home' }

checkStatus:
   path: /checkStatus
   defaults: { _controller: 'App\Controller\PagesController::test' }

readSingle:
   path: /readSingle/{id}
   defaults: { _controller: 'App\Controller\PagesController::readSingle' }
